name: Build and Push

on: [push]

jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install flake8
        run: pip install flake8
      
      - name: Run flake8
        run: flake8 . --ignore E501,W503,E203,E266,W292,E302,E305 --exclude venv

  deploy:
      name: Deploy container
      runs-on: ubuntu-latest
      needs: python-formatting
      if: github.event_name == 'push' && contains(github.ref, 'main')
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: Log in to GitHub Container Registry
            uses: docker/login-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.GH_DEPLOYER }}
                password: ${{ secrets.GH_TOKEN }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v4
            with:
                context: .
                push: true
                tags: ghcr.io/travelator/generation-api:latest
